package model.node

data object AssignNode : NodeType
data object AssignStatementNode : NodeType
data object BinaryOperationExpressionNode : NodeType
data object BlockNode : NodeType
data object BooleanLiteralNode : NodeType
data object BooleanTypeNode : NodeType
data object ColonNode : NodeType
data object ConstDeclarationStatementNode : NodeType
data object ConstNode : NodeType
data object DivideNode : NodeType
data object ElseBlockNode : NodeType
data object ElseNode : NodeType
data object IdentifierNode : NodeType
data object IfNode : NodeType
data object IfStatementNode : NodeType
data object LeftBraceNode : NodeType
data object LeftParenthesisNode : NodeType
data object LetDeclarationStatementNode : NodeType
data object LetNode : NodeType
data object MinusNode : NodeType
data object MultiplyNode : NodeType
data object NumberLiteralNode : NodeType
data object NumberTypeNode : NodeType
data object ParenthesizedExpressionNode : NodeType
data object PlusNode : NodeType
data object PrintlnKeywordNode : NodeType
data object PrintlnStatementNode : NodeType
data object ReadEnvExpressionNode : NodeType
data object ReadEnvKeywordNode : NodeType
data object ReadInputExpressionNode : NodeType
data object ReadInputKeywordNode : NodeType
data object RightBraceNode : NodeType
data object RightParenthesisNode : NodeType
data object SemicolonNode : NodeType
data object StringLiteralNode : NodeType
data object StringTypeNode : NodeType
data object UnaryOperationNode : NodeType
